#!/usr/bin/python
import pandas as pd

import parse_arff

#from naive_bayes_tan import NaiveBayes
train_parser = parse_arff.ARFF_Parser()
#test_parser = parse_arff.ARFF_Parser()
train_parser.parse('sonar.arff')
#test_parser.parse(sys.argv[2])
train_data = pd.DataFrame(train_parser.data)
#test_data = pd.DataFrame(test_parser.data)
#nb_classifier = NaiveBayes(train_parser,sys.argv[3])
#nb_classifier.fit(train_data)
#nb_classifier.predict(test_parser.data)
print train_data